import Head from 'next/head'
import styles from '../styles/Home.module.css'
import moment from 'moment';
import {useState, useRef} from "react"

import Footer from '../components/Footer'

export default function Home() {
  let [lock, setLock] = useState(true)
  let time = moment().format("h:mm")
  let date = moment().format("dddd, MMMM D")
  const pageRef = useRef()

  const unlock = () =>{
    if(lock){
      setLock(false)
    }
    return;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homepage} ref={pageRef} onClick={()=>unlock()}>
          <div className={lock ? styles.lockscreen : `${styles.lockscreen}  ${styles.visibility}`}> 
              <p className={styles.time}>{time}</p>
              <p className={styles.date}>{date}</p>
              <p className={styles.unlock}>touch to unlock</p>
          </div>
          {
            !lock && <><Footer/></>
          }
      </div>

    </>
  )
}
